/*******************************************************************************
 * BEGIN COPYRIGHT NOTICE
 * 
 * This file is part of program "cobolg"
 * Copyright 2016  Rodrigo Lemos
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * END COPYRIGHT NOTICE
 ******************************************************************************/
package br.eti.rslemos.cobolg;

import java.util.ResourceBundle;

import org.junit.Test;

import br.eti.rslemos.cobolg.COBOLParser.StmtPERFORMimperativeContext;
import br.eti.rslemos.cobolg.Waive.CompilationError;

@Waive({CompilationError.EXACT_AMBIGUITY, CompilationError.FULL_CONTEXT_ATTEMPT})
public class StmtPERFORMimperative {
	private static final ResourceBundle TEST_DATA = ResourceBundle.getBundle("br.eti.rslemos.cobolg.stmtPERFORMimperative");
	public static String get(String key) { return TEST_DATA.getString(key); }

	private static CompilerHelper<StmtPERFORMimperativeContext> helper = new CompilerHelper<StmtPERFORMimperativeContext>() {
		@Override protected StmtPERFORMimperativeContext parsePart() { return parser.stmtPERFORMimperative(); }
	};

	@Test public void PERFORM_PROC_1() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1.source"),
				get("PERFORM_PROC_1.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THROUGH_PROC_2() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THROUGH_PROC_2.source"),
				get("PERFORM_PROC_1_THROUGH_PROC_2.tree")
			);
	}

	@Test public void PERFORM_PROC_1_N_TIMES() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_N_TIMES.source"),
				get("PERFORM_PROC_1_N_TIMES.tree")
			);
	}

	@Test public void PERFORM_PROC_1_10_TIMES() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_10_TIMES.source"),
				get("PERFORM_PROC_1_10_TIMES.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_N_TIMES() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_N_TIMES.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_N_TIMES.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_10_TIMES() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_10_TIMES.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_10_TIMES.tree")
			);
	}

	@Test public void PERFORM_PROC_1_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_BEFORE_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_AFTER_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_AFTER_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_WITH_TEST_AFTER_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_K_STEP_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_K_STEP_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_K_STEP_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_10_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_10_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_10_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_K_STEP_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_K_STEP_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_K_STEP_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_WITH_TEST_BEFORE_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_10_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_10_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_WITH_TEST_AFTER_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_10_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_10_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_10_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_10_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_N_LOW_BY_N_STEP_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_K_STEP_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_K_STEP_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_0_BY_K_STEP_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_N_LOW_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_10_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_10_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_10_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_0_BY_N_STEP_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_M_STEP_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_K_STEP_UNTIL_K_OP_GREATER_M() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_K_STEP_UNTIL_K_OP_GREATER_M.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM_M_LOW_BY_5_UNTIL_M_OP_EQUAL_20_AFTER_K_FROM_K_LOW_BY_K_STEP_UNTIL_K_OP_GREATER_M.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_BEFORE_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0_AFTER_M_FROM__10_BY_M_STEP_UNTIL_M_OP_EQUAL_20.tree")
			);
	}

	@Test public void PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0() {
		helper.compileAndVerify(
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0.source"),
				get("PERFORM_PROC_1_THRU_PROC_2_TEST_AFTER_VARYING_N_FROM_0_BY__2_UNTIL_N_OP_LESS_0.tree")
			);
	}
}
